#!/bin/bash
#Author=
#Purpose=
#Creation date=
#Modificaton date=
# creating the of file with previous date and time 
#touch -d "Mon 5 June 2021 12:23:15" Oldfile{1..5}.txt

# find the 90 days old files
#find /var/log -mtime +90 -exec ls -l {} \;
# rename the old files
#find /opt/scripts -mtime +90 -exec mv {} {}.new \;

# Deleting the old 90 days files 
#find /opt/scripts -mtime +90 -exec rm {} \;

# archive the file , compress and move to the remote host or remote destination
#tar -cvf /tmp/backup.tar /var/log
#gzip /tmp/backup.tar
#find /tmp/backup.tar.gz -mtime -1 -type f -print &> /dev/null
#if [ $? -eq 0]
#then 
#echo "backup sucess created"
#echo " archive also created"
#scp /tmp/backup.tar.gz root@172.168.10.44:/data/backupstorage
#else 
#echo "backup failed"
#fi

# To known the login user details
# echo "please enter day (e.g Mon)"
#read day
#echo "please enter Month (e.g jun)"
#read Month
#echo "please enter date (e.g 17)"
#read date
#echo
#last | grep "$day $month $date"
#last

# To check the current date
#echo "Current time is $(date)"

# find the file with .txt and move to .html
#filename=`find /tmp/scripts/ -name "*.txt" | cut -d "." -f1`
#for i in $filename
#do
#mv $i.txt $i.html
#done

#To check the size of file in directory
dir=/tmp
#for file in $dir/* ;
#do 
#echo "file $file is $(stat --printf='%s' $file) Bytes."
#done

#du -sh /tmp

#To check the service status 
read -p "Enter your of service="  service
status=$(systemctl status $service)
echo -e  "this show the status\033[96m $status\033[0m"  # \033[88m is print in color where you select

#!/bin/bash
#This is used to start and stop httpd service
read -p "Enter start,stop,status,enabled,and Disabled  to perform action on httpd service: " action
read -p "Enter the Service name=" Service_name
Systemtcl=$(systemctl ${action} ${Service_name})

if [ "${action}" == "start" ]
then
echo "${action} ${Service_name}...."
echo"$Systemtcl" #echo"$Systemtcl" # systemctl ${action} $(Service_name)
 echo "${action} ${Service_name}"
fi

if [ "${action}" == "stop" ]
then
  echo "${action} ${Service_name}"
echo "$Systemtcl" # systemctl ${action} $(Service_name)
# systemctl ${action} $(Service_name)
 echo "${action} ${Service_name}"
fi


if [ "${action}" == "status" ]
then
 echo "stopping ${Service_name}..."
echo"$Systemtcl" # systemctl ${action} $(Service_name)
# systemctl ${action} $(Service_name)
 echo "${action} ${Service_name}"
fi

                                                        
